server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: root
    password:

  kafka:
    consumer:
      group-id: app.1
    bootstrap-servers: localhost:9092

  h2:
    console:
      path: "/h2"
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
